### ISSUE TITLE
[2.4.5] Language is set traditional Chinese, return value of cc.sys.language is en, and the languageCode is en-us on Android.

### ISSUE THREAD

**Issue by zyqq** [cocos/cocos-engine#10107]
### Creator version?（版本号）
2.4.5

### Affected platform?（受影响的平台）

安卓12 oppo reno5pro
### How to reproduce?（如何重现）
手机系统语言设置繁体返回的cc.sys.language是en，languageCode是en-us
![anzuofanti](https://user-images.githubusercontent.com/15664576/153979420-f411eaf4-b2b2-49bf-8487-bd5de750aa26.png)

### JavaScript output or error produced?（报错信息和调用栈）

<img width="1168" alt="cocosdabao" src="https://user-images.githubusercontent.com/15664576/153979190-bb6f786b-62c9-423a-a4bf-f8e0047044be.png">

**Comment by zyqq** [comment]
补充测试：vivo 安卓10设置繁体就返回正常，android stuiod打包也正常，oppo安卓12如果语言列表里除了繁体以外没有简体以及英文也返回正常
因此考虑是cocos打包对安卓12有影响，会导致系统错误判断不支持的语言导致返回下一个语言

**Comment by minggo** [comment]
@timlyeee 有时间看下这个问题。

**Comment by timlyeee** [comment]
Test on Android 12, if there's no Simplified Chinese, the order of language is wrong. 
![image](https://user-images.githubusercontent.com/43355299/179692125-18e0cfbd-9304-4689-bb0a-adbba50ab111.png)
![image](https://user-images.githubusercontent.com/43355299/179692155-47a0d0fa-5726-4a3b-9c54-8f9552343f0b.png)
The reason is that if we don't offer a value resource file of specified language, the system will give APP a default language value as english. Also, the order of language influence the result too.

## Situation 1

System language: Traditional Chinese, Simplied Chinese, English.
App language that set by the system: zh_TW, zh_CN, en_US
App language by default: zh_TW, zh_CN, en_US

## Situation 2

System language: Traditional Chinese, English.
App language that set by the system: en_US, zh_TW 
App language by default: zh_TW, en_US

## Situation 3: value resource file with zh_TW

System language: Traditional Chinese, English.
App language that set by the system: zh_TW , en_US
App language by default: zh_TW, en_US

to keep the behavior respectively, just change the call of API

**Comment by timlyeee** [comment]
Fix to 2.4.10 and 3.6
