### ISSUE TITLE
Remove deprecated APIs from Creator 3D v1.x

### ISSUE THREAD

**Issue by pandamicro** [cocos/cocos-engine#10644]
Our engine have been published since 2019 with a dedicated version Cocos Creator 3D, it has been merged into Cocos Creator v3.0 in 2021. It's been a while since some features have been deprecated in dedicated version, we need to do some cleanup, @holycanvas @minggo please take some time for it.

Welcome for any contribution too

**Comment by minggo** [comment]
https://github.com/cocos/cocos-engine/pull/10656 remove some deprecated api

**Comment by minggo** [comment]
I reverted the modification in https://github.com/cocos/cocos-engine/pull/10694, because:
- there is not warning message of deprecated API, which means these API are not really deprecated, developers do not know it
- deserialization depends on deprecated classes name

So we can delete these API when:
- developers knows these API are deprecated
- editor doesn't depends on deprecated class names
- it is a big release version, such as v4.0

But we can remove the usage of these deprecated API in engine codes and demos.
