### ISSUE TITLE
uninterrupted signal transmission was broken after iOS game restart.

### ISSUE THREAD

**Issue by xianyinchen** [cocos/cocos-engine#10674]
### Cocos Creator version

3.5.0

### System information

iOS 15.4 build on iphone 12 mini

### Issue description

terminate the game application (no use cc.game.restart), reopen application the download received bytes will start from zore, I think the uninterrupted signal transmission was broken.

 

### Steps to reproduce

video:
https://user-images.githubusercontent.com/8321365/162106554-e97a4b77-31be-4fb4-8b83-ed2ae92478bc.mp4

example code:
``` typescript

import { _decorator, Component, Node, Label } from 'cc';
const { ccclass, property } = _decorator;

@ccclass('test')
export class test extends Component {

    @property(Label)
    text: Label = null!;

    down () {
        let down = new jsb.Downloader();
        down.setOnTaskProgress((task, recv, total)=>{
            console.log(recv, total)
            this.text.string = total.toString();
        })
        let task = down.createDownloadFileTask('https://download.cocos.com/CocosCreator/v2.3.1/CocosCreator_v2.3.1_20200303_win.7z', jsb.fileUtils.getWritablePath() + '/zz');
    }

}
```

**Comment by novain1102** [comment]
The current uninterrupted signal transmission implementation does not support restart operation (related to terminate app). Consider reimplementing the above function in the future. @minggo

**Comment by minggo** [comment]
Got it, so it is a new feature request. Change to v3.6.

**Comment by novain1102** [comment]
Currently, If you use game.restart() to restart the engine, uninterrupted signal transmission should be work(as your description shows). And if you click close button and reopen the App, uninterrupted signal transmission couldn't work. So what are the specific needs of users? @xianyinchen

**Comment by xianyinchen** [comment]
Usually, the mobile application will only be switched to the background, but users expect the app to close and need support breakpoint continuation work.

**Comment by novain1102** [comment]
The old version downloader DO NOT support break-point download when killApp, and the reason is below:
When the process is killed in the appDelegate, the -applicationWillTerminate: method is called. We expect the task to call the cancelByProducingResumeData: method to suspend the downloading task, but the callback of this method takes time, and the process has terminated before the code block is executed.
The solution is to find the previously in-progress task every time a session is created (that is, the task that was killed, cancels it and saves ResumeData for later use when creating the same task).
But this method may lead to execution timing problem, because we use the concept of block in ios, and its execution time will be placed in the next time slice. Therefore, in order to ensure that resumeData is saved and used for the next time the task is created. I've tried the following:
1. put `createSession` and `createTask` in seperate thread, and sleep
createTask before createSession work ready : The disadvantage is that it will cause the main thread to block, which is risky, although it works.
![4461651757370_ pic](https://user-images.githubusercontent.com/18634782/167090314-4498763f-1b54-49b2-9d0b-5373067e9b3e.jpg)

2. put `createTask` run `delay in next frame`: The time reserved by this method is not enough to ensure that the work related to `createSession` is completed and `resumeData` is used in the subsequent createTask phrase. So it doesn't work.
![4451651757306_ pic](https://user-images.githubusercontent.com/18634782/167090324-0be30db5-7a3c-4d00-9591-36ef95a578b1.jpg)
![4501651823842_ pic](https://user-images.githubusercontent.com/18634782/167091427-b7349f16-86e1-47f3-993d-42cacf4b1c2e.jpg)

3. put `createTask` run `delay in specific time`(https://github.com/cocos/cocos-engine/pull/10968): After testing, the minimum time to ensure that the execution as expected is 100ms, which means that there will be a delay of at least 100ms after the user creates a task, but I think this is acceptable compared to other methods.
<img width="1336" alt="image" src="https://user-images.githubusercontent.com/18634782/167090788-9d1a5a75-af19-4a4f-95a9-b3150604633a.png">

![4521651823944_ pic](https://user-images.githubusercontent.com/18634782/167091937-d849c2a9-ffce-49bb-aa25-37b4ccb8eb47.jpg)

**Comment by novain1102** [comment]
Android breakpoint download function also fixed in above PR :)
