### ISSUE TITLE
[3.5-dev] Mac application requires a more explicit gate to implement user codes.

### ISSUE THREAD

**Issue by timlyeee** [cocos/cocos-engine#10704]
![image](https://user-images.githubusercontent.com/43355299/162408796-f2004368-aded-4826-a279-cdb0be6a6c53.png)

For Mac on 3.5, only the main.mm is left for the developer's project, which is difficult to use, and right now there's no 3rd-party SDK for the project, such as Ad or whatever it is, but one day it might be considered.

## Why should we offer an easy way to implement user's code?

I'm probably influenced by Android, but AppActivity is something that can be inherited, and the developer can access the life cycle here, and code as they want.

As for Mac, one can only override main.mm to full fill the need.

## How to implement the developer's code?

One can override main.mm like this:
```cpp
#include <iostream>

//#include "platform/BasePlatform.h"
#include "MyPlatform.h"//Indeed, what is it? Platform?
#define START_MY_PLATFORM
...
int main(int argc, const char * argv[]) {
    START_MY_PLATFORM(argc, (const char**)argv);
}

```

and then write his own MyPlatform:

```cpp
...
@implementation MyMacPlatform: MacPlatform
-(void)onInit:(...){
 superInit();//Just call parent's method.
 myCode();//Here goes my code for life cycle, or others
}

@end
...

```

BasePlatform and MacPlatform is actually good mechanism as it actually provides a lot of methods to insert codes. 

**BUT** 
1. It's hard to find and hard to understand. 
2. Seriously? I don't even understand what it means "start a platform".🤣

## My guess

Maybe we should consider exposing platform files to the template rather than let the developer dig and find it. And iOS might no more need to expose AppDelegate, iOSPlatform is sufficient.

**Comment by qiuguohua** [comment]
First of all, you need to understand the concept of platform and application. The concept of platform is a foundation on which many applications will run. The original intention of the design is to try to prevent users from paying too much attention to the platform, because the characteristics of different platforms are different, which is not conducive to a cross-platform application.

Most of the developed business logic should be concentrated in the application, and the dependence on the platform should be completed through the internal platform class or interface, so that the future expansion and modification are controllable.

In the design of this V3.5 version, the platform layer is initialized in the main because some special platform operations are really needed sometimes, but it is recommended to avoid doing so as much as possible. Because this is not cross-platform, it will also cause some burdens on maintenance and upgrades.

In IOS, there is a more special, third-party SDK access, you need to use AppDelegate directly. Because some developers don't know much about C++ and think it is difficult to use game to connect. In order to maintain the compatibility of the interface, the IOS side was first moved to the template layer

> It's hard to find and hard to understand.

The platform is similar to the system, but it is also very different from the system. I think in your demo, is it better to change 'MyMacPlatform' to 'CustomMacPlatform'?
Or is there a better suggestion?

> Seriously? I don't even understand what it means "start a platform".🤣

Since the platform is similar to the system, the start platform is similar to starting the system or booting, it may be better to change it to startup

**Comment by minggo** [comment]
@timlyeee can close it now?
