### ISSUE TITLE
Webp compress texture building error

### ISSUE THREAD

**Issue by yoki0805** [cocos/cocos-engine#11014]
### Cocos Creator version

3.5.0

### System information

web-mobile

### Issue description

Webp compress texture building error.

### Relevant error log output

[Build] [compress webp]Error! 'undefined' is not a floating point number.

### Steps to reproduce

1. setup compress texture: webp quality 80.
2. select a image, set useCompressTexture toggle on.
3. build project.

**Comment by Ronsku** [comment]
I'm also wondering about this! Isn't the WEBP Compression working?

**Comment by Ronsku** [comment]
I took an webp Image from my build and ran it through another compression tool. It clearly doesn't work in CC3.5, because it compressed the image a lot!
![image](https://user-images.githubusercontent.com/7983358/168030021-54de983c-615e-49a1-8a7b-ce6fe81a3007.png)

**Comment by Ronsku** [comment]
@yoki0805 I think you can solve your issue by re-doing your custom texture compression setups for your project. The structure has changed like this:
![image](https://user-images.githubusercontent.com/7983358/168060145-de98670f-f9f9-4456-b6f3-305187894a09.png)

**Comment by yoki0805** [comment]
I will try it. Thank you.

**Comment by Ronsku** [comment]
I think we can close this ticket.
For developers, this is an issue with upgrading from cc 3.4.x -> 3.5.0 where the structure of the compression config has changed to an object with "quality" property instead of just a number. This is not an issue with new project that starts from 3.5.0.
This should probably be written in the upgrade breaking changes.
