### ISSUE TITLE
vertex input attribute is missing in macro

### ISSUE THREAD

**Issue by star-e** [cocos/cocos-engine#11062]
### Cocos Creator version

3.4.2

### System information

Windows

### Issue description

shader input attribute will be missing, if it is in macro's both branches.

### Steps to reproduce

put input attribute in to macro's both branch, in any shader

**Comment by yiwenxue** [comment]
The parser will assign a "requirement" to each attribute in our effect system, and this so-called "requirement" is controlled by shader Macros. For example, 
```glsl
#if HAS_NORMAL
in vec3 a_normal;
#endif
```
, the "requirement" of `a_normal` is `HAS_NORMAL1`.

The problem is that this "requirement" only supports `and` logic (without `or`).
```glsl
#if HAS_NORMAL
in vec3 a_normal;
#else
in vec3 a_normal;
#endif
```
In the second code segment, the "requirement" of `a_normal` is "HAS_NORMAL1, HAS_NORMAL0". This requirement can never be fitted.

**Comment by star-e** [comment]
Not going to fix.
