### ISSUE TITLE
Some errors in creator.d.ts 

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#11731]
### Cocos Creator version

2.4.9

### System information

all

### Issue description

`DynamicAtlasManager  insertSpriteFrame().`  should return  Frame (not void)

`TiledMap.enableCulling(value:any)`  , the method should be  getter & setter , value type is boolean

`TiledLayer.enableCulling(value:any)`  the argument should be boolean. 

### Steps to reproduce

when use these the method  in typescript

**Comment by finscn** [comment]
declare let CC_JSB: boolean
declare let CC_EDITOR: boolean
declare let CC_PREVIEW: boolean
declare let CC_TEST: boolean
declare let CC_DEBUG: boolean

以上变量被重复定义. 报错信息如下: 

Identifier 'XXXXXX' has already been declared.

**Comment by tuyazuo** [comment]
`removeCache(): void;`   need one argument

**Comment by minggo** [comment]
@PPpro is it fixed in v3.6?

**Comment by PPpro** [comment]
they've been fixed since 3.x

**Comment by minggo** [comment]
Will sync to v2.x?

**Comment by PPpro** [comment]
> Will sync to v2.x?

sync here 
https://github.com/cocos-creator/creator-api-docs-2.x/pull/204 
https://github.com/cocos/cocos-engine/pull/11981


In consideration of interface compatibility， `enableCulling` is still designed as a function, won't be a setter/getter  
while we've changed the  `enableCulling`  into a setter/getter since v3.x

**Comment by PPpro** [comment]
thanks for feedback
