### ISSUE TITLE
Browser preview: when gaining focus, game should not be automatically resumed if it was manually paused

### ISSUE THREAD

**Issue by shrinktofit** [cocos/cocos-engine#12331]
Steps:

- Launch the preview.

- Click the `pause` button in preview toolbar so that the game is paused by desire.

- Switch to another browser tab and switch back, or minimize the browser window then revert. You can see the game will be automaticlly resumed.

Resume call stack:

![image](https://user-images.githubusercontent.com/28807867/182778313-c947e13c-73c6-4fb0-94b6-fddf0fce5c3c.png)

**Comment by qiuguohua** [comment]
I reproduce this bug because every time the tab is switched or zoomed out, the onHide message and the onShow message are triggered. The onHide message will pause the game (if the game state is already paused, it will not be processed), and if the onShow message will resume. The reason here is to reuse a state.
