### ISSUE TITLE
canvas does not trigger resize [Alipay]

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#12375]
### Cocos Creator version

3.5.2，3.6.0-080521

### System information

window10

### Issue description

https://forum.cocos.org/t/topic/138507
![image](https://user-images.githubusercontent.com/40415168/183613791-05da0de3-4e76-4163-bf1d-02e45b85b0a7.png)
![image](https://user-images.githubusercontent.com/40415168/183614108-d90b2b3d-48d2-48e2-b41e-a0dcbb92c6a4.png)

![image](https://user-images.githubusercontent.com/40415168/183614225-9a8ad8e3-eee5-489c-ad3b-620fd412677b.png)
You can see that the input is moved up, but the canvas does not trigger the resizeFrame properly.

### Steps to reproduce

1. create a editbox node;
2. Use Alipay to scan the code：
![image](https://user-images.githubusercontent.com/40415168/183614054-1acd9077-6d2f-48ce-a2b5-17a7c0f9fc78.png)

**Comment by minggo** [comment]
@timlyeee  please take a look. If you need any help, can ask @PPpro .

**Comment by timlyeee** [comment]
This issue is totally wrong!!! It's not how it works!

Editbox is a DOM element on web, and when the user is trying to input some text, this dom element will scroll up with the DOM API `scrollIntoView`. 

Alipay's web browser does not support this API so the behavior becomes like this. But we cannot detect if it's a Alipay browser or something else....

Please checkout if Alipay mini game has the same issue and that's what we're digging in. @OnlyKoei

**Comment by zhefengzhang** [comment]
此问题属于支付宝软件中的 webview 环境独有的问题，属于支付宝软件的功能缺陷，不是引擎所使用的标准 web api 所能解决的。
用户如果遇到此问题，可以建议针对这个运行环境停止对 edit-box-impl.ts 中的 _adjustWindowScroll 函数的执行。
<img width="887" alt="图片" src="https://user-images.githubusercontent.com/35944775/220270983-5ea6daa6-9eb7-49fc-a568-9efc72d1d243.png">

问题关闭。
---

This problem is unique to the webview environment in the Alipay software and is a functional defect of the Alipay software that cannot be solved by the standard web api used by the engine.
Users who encounter this problem can suggest stopping the execution of the _adjustWindowScroll function in edit-box-impl.ts for this runtime environment.
<img width="887" alt="图片" src="https://user-images.githubusercontent.com/35944775/220270983-5ea6daa6-9eb7-49fc-a568-9efc72d1d243.png">

Close.
