### ISSUE TITLE
Unify coding style of math library in native

### ISSUE THREAD

**Issue by minggo** [cocos/cocos-engine#12728]
Some functions such as `Vec3::leap` and `Quaternion::lerp` has different coding style:
```c++
// Vec3
inline Vec3 lerp(const Vec3 &target, float alpha) const;

// Quaternion
static void lerp(const Quaternion &q1, const Quaternion &q2, float t, Quaternion *dst);
```
- one is static, another isn't
- one return a temple instance, one requires passing in a pointer

And @shrinktofit also has a new implementation of it https://github.com/cocos/cocos-engine/pull/12719. Just implement it outside of Vec3 and Quaternion.

So should discuss the coding style: should implement in class or a global function in cc namespace.

**Comment by stanleyljl** [comment]
I recommend implementing these interfaces inside the class, static and non-static functions can exist at the same time, and try to avoid polluting the names in the cc namespace. If it's just a pure C++ version, it's also appropriate to use a global template function, but it's not recommended for consistency with TS. @minggo

**Comment by minggo** [comment]
@stanleyljl i agree with you.

**Comment by shrinktofit** [comment]
I'd like to proposal some styles:

- No need to be consistent with TypeScript math since we no longer need the verbose `out` parameters.

- If a math operation is subject to only few or specific math concepts, implement it as class member. For example:

  - Quaternion conjugation, constructing a quaternion from axis and angle.

  - Vector projection on plane, vector angle calculation.

  - Matrix trace calculation, determinant calculation.

- If a math operation is well-known and commonly used and exists in most math concepts, implement it in namespace `cc` or `cc::math` so we can use it by `cc::normalize(quat)`, `cc::normalize(vec3)`. For example:

  - Arithmetic operations(+-*/) on scalars, vectors, quaterions, matrices.

  - Normalization on vectors, quaternions.

  - Linear interpolation on scalars, vectors, quaternions, matrices.

  - Spherical interpolation on vectors, quaterinions.

  - Inverse on scalars(reciprocal), quaternions, matrices.

  I don't think this introduce name pollution since C++ function overloading is designed for and benifit from it.

**Comment by minggo** [comment]
> If a math operation is well-known and commonly used and exists in most math concepts, implement it in namespace cc or cc::math so we can use it by cc::normalize(quat), cc::normalize(vec3). For example

In this specific case, `cc::normalize(quat)` and `cc::normalize(vec3)` need to know the layout of Quaternion and Vec3. Similarities between the two classes just the function name and its meaning, but their implementation are very different. So i don't know the benefit of it.

**Comment by shrinktofit** [comment]
Why do cc::normalize(quat) and cc::normalize(vec3) need to know the layout of Quaternion and Vec3?

**Comment by minggo** [comment]
Currently, it doesn't is just because there is `Vec3::lerp` and `Quaternion::lerp`, and your implementation is just a wrapper of these functions.

**Comment by shrinktofit** [comment]
Two functions with same name but have different implementation is just what the function overloading does.

**Comment by minggo** [comment]
Yep, i know C++ overloading. Let's make things more clear. Did you mean should delete `Vec3::lerp` and `Quaternion::lerp`, just keep `cc::lerp`?

**Comment by shrinktofit** [comment]
> Yep, i know C++ overloading. Let's make things more clear. Did you mean should delete `Vec3::lerp` and `Quaternion::lerp`, just keep `cc::lerp`?

yes as described by above proposal.

**Comment by minggo** [comment]
Got it. Any benefit of it? As we should break compatibility, if there is not not any benefit, then i don't think should change it.
