### ISSUE TITLE
Sliding screen causes audio playback to fail

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#13065]
### Cocos Creator version

3.6.1

### System information

window10

### Issue description

https://forum.cocos.org/t/topic/141252
![image](https://user-images.githubusercontent.com/40415168/196137399-8a162900-2f69-4261-acc1-ed3f34a1ee38.png)

### Steps to reproduce

demo:
[NewProject_8.zip](https://github.com/cocos/cocos-engine/files/9798842/NewProject_8.zip)

**Comment by timlyeee** [comment]
This issue is mainly caused by the safety policy of Web, the 'touchend' event caused by slide and the 'touchevent' caused by click does not means the same for browser. 

I've reported the bug for webkit and chrome.

https://bugs.chromium.org/p/chromium/issues/detail?id=1392959

https://bugs.webkit.org/show_bug.cgi?id=248265

Right now what we can do is to jump across this issue.

**Comment by timlyeee** [comment]
@bofeng-song Keep watching at the feedback of chromium and webkit
