### ISSUE TITLE
Model rendering issue in byte-dance platform

### ISSUE THREAD

**Issue by linruimin** [cocos/cocos-engine#13129]
### Cocos Creator version

3.4.2

### System information

huaweiP30pro

### Issue description

The model renders fine on the editor and web, and fine on the byte-hop developer tool, and does not display properly on today's headlines when tested with the real machine.
in web:
![image](https://user-images.githubusercontent.com/18083506/197476195-58f81990-a7f0-462f-a3bd-b973fb065a7e.png)
in real machine:
![03970af2e28c76625d6b65fb72b5b88](https://user-images.githubusercontent.com/18083506/197476262-ca296a41-ccb2-4085-8091-b93ec60c10d6.jpg)

### Steps to reproduce

here is the demo:
[caiZhiQiu.zip](https://github.com/cocos/cocos-engine/files/9849882/caiZhiQiu.zip)

**Comment by pandamicro** [comment]
It's probably due to texture format support issue on the target platform, based on the following checks:

1. The shader and render command submission are successfully executed, because it's rendering black and white outline
2. The outline is ok meaning the mesh is correctly recognized
3. Other elements like tree are rendering ok meaning the shader has no issue

**Comment by yyycggg** [comment]
This is due to the fact that the texture of this model's material is a texture with alpha channel, but the shader does not support textures with alpha channel.

When it gets the color of the pixel point is pure transparent, that is `Vec4(0, 0, 0, 0)`, but this shader's color blending mode is not blended with alpha channel, which means the final color is `Vec4(0, 0, 0, 1)`, that is black.

**Comment by linruimin** [comment]
The byte-dance platform shows normal after change the transparent part of the semi-transparent texture map to full white.
![1cd94f2d3fed2382b37351533b8d77b](https://user-images.githubusercontent.com/18083506/198921905-3c10295d-976d-4014-adde-d9ea29f6a907.jpg)
