### ISSUE TITLE
Click Callback Exception

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#13542]
### Cocos Creator version

3.6.2

### System information

window10, chrome

### Issue description

https://forum.cocos.org/t/topic/142427
![image](https://user-images.githubusercontent.com/40415168/203726472-7c52d528-9916-44e6-ac7e-909eec48092b.png)

### Steps to reproduce

demo:
[aaa.zip](https://github.com/cocos/cocos-engine/files/10081932/aaa.zip)
![企业微信截图_16684774854011](https://user-images.githubusercontent.com/40415168/203726562-e5c8ca75-0a85-4b44-a504-0cb471379d53.png)

**Comment by minggo** [comment]
When a node handles the `TOUCH_START` event, it will be able to handle `TOUCH_END`. In this issue,
- A, B handle the first `TOUCH_START` event, so they will be able to handle the `TOUCH_END` event. But the first `TOUCH_END` event is handled by C, so A, B are still able to handle the `TOUCH_END` event.
- When second `TOUCH_END` event arrives, it will be handled by A as A has the highest priority, and will swallow it. So B and C don't receive the `TOUCH_END` event.

I will try to fix it like this: when any node handles the `TOUCH_END` event, should clear all other handles's state, make them be not available to handle the `TOUCH_END` event.

**Comment by minggo** [comment]
First touch is triggered in the overlapped area of A and B. Second touch is triggered in C and out of A and B.

The reason is that:
- first `TOUCH_START` event arrives, then
  - A will handle it, so A is able to handle `TOUCH_END` event
  - B will handle it, as A doesn't swallow event, so B is able to handle `TOUCH_END` event
  - C will handle it three times, and it will able to handle `TOUCH_END` event
    - first one is because A, B doesn't swallow event, so it will handle it
    - second one is because C is the father of A and B, so the event will be propagated to C twice
- first `TOUCH_END` event arrives, then
  - A will handle it, then it is unable to handle `TOUCH_END` event
  - B will not handle it as A will swallow the event
  - C will handle it as it is the father of A
- second `TOUCH_BEGIN` arrives, then
  - A and B will not handle it as it is out of A and B content(will do hit test with `TOUCH_BEGIN` event)
  - C will handle it
- second `TOUCH_END` arrives, then
  - B will handle it, as it is out of B's content, so the event will be changed to `TOUCH_CANCEL`
  - C will handle `TOUCH_CANCEL` event, not the `TOUCH_END` event
