### ISSUE TITLE
[3.7] upgrade from 3.6, the sprite show diferrent transparency

### ISSUE THREAD

**Issue by xianyinchen** [cocos/cocos-engine#14169]
### Cocos Creator version

3.6.7

### System information

Window Editor

### Issue description

diferrent transparency in Editor, also on webbrowser preview.

![image](https://user-images.githubusercontent.com/8321365/217418521-7391fb8a-a1e3-47a9-a962-334f35af8ada.png)

another situation such as chrome mobile mode and pc mode has diferrent transparency (engine use webgl1 only).

![1675826204690](https://user-images.githubusercontent.com/8321365/217419977-8f5c592a-9fa5-45f2-b22b-e92ad2025828.png)

![企业微信截图_16758262325993](https://user-images.githubusercontent.com/8321365/217420031-f3595a71-91b8-47e2-aad5-43c73661b1a2.png)

### Steps to reproduce

ask me for test resource.

**Comment by bluesky013** [comment]
![企业微信截图_16759243636059](https://user-images.githubusercontent.com/35895395/217735771-795ea57b-0c0f-4a3d-ab54-0eae89f21cc0.png)

> `UNPACK_FLIP_Y_WEBGL`, `UNPACK_PREMULTIPLY_ALPHA_WEBGL`, `UNPACK_COLORSPACE_CONVERSION_WEBGL`
> If the TexImageSource is an ImageBitmap, then these three parameters will be ignored.

We seem to have changed the texture data to `ImageBitmap` in v3.7.0

**Comment by bluesky013** [comment]
The `AssetManager` converts a blob of an image into an `ImageBitmap` or `HTMLImageElement` based on 2 conditions.
1. `sys.Feature.IMAGE_BITMAP` is enabled.
2. `AssetManager.allowImageBitmap` is set, default value `!mobile`.

`sys.Feature.IMAGE_BITMAP` was incorrect for earlier versions and fixed in v3.7.0. [FIX](https://github.com/cocos/cocos-engine/pull/13165)

If the TexImageSource is an ImageBitmap, `UNPACK_PREMULTIPLY_ALPHA_WEBGL` will be ignored.

This explains why it fails in editor and web browser, but succeeds in mobile mode.

Solusion:
Set `assetManager.allowImageBitmap` to false before `gl.pixelStorei(gl.UNPACK_PREMULTIPLY_ALPHA_WEBGL)` in test script.
