### ISSUE TITLE
Wrong position of cascade child node

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#14570]
### Cocos Creator version

3.7.1

### System information

window 10

### Issue description

https://forum.cocos.org/t/topic/146993
![image](https://user-images.githubusercontent.com/40415168/224934053-ec3249e5-2cf9-4f8b-a4bd-6e810be0d567.png)

normal:
![企业微信截图_1678779389472](https://user-images.githubusercontent.com/40415168/224934227-5a568e11-49a1-41ca-9455-eeb02af43af8.png)

after merge this pr : https://github.com/cocos/cocos-engine/pull/14381
Change the position of the parent node:
![企业微信截图_16787793831312](https://user-images.githubusercontent.com/40415168/224934517-a7e76685-96b5-477c-9741-b375fef6344f.png)

### Steps to reproduce

demo :
[cocos-tutorial-hot-update.zip](https://github.com/cocos/cocos-engine/files/10965606/cocos-tutorial-hot-update.zip)

**Comment by LinYunMo** [comment]
This problem is due to the fact that when handling transparency to avoid useless rendering, the rendering is directly skipped when transparency is detected as 0 for better performance, and when transparency is restored, the position update tag of the child node is disabled, so the position is no longer updated.
Two options are available here:
- Set all update labels of its children nodes together when transparency changes, but it is too inefficient
- Incorporate transparency change management into the overall update triggering, but requires refactoring the system due to transparency cascading issues

------------------------------------------------------------------------------------------------------------------------

这个问题是由于在处理透明度避免无用渲染时，检测到透明度为 0 时直接跳过了渲染以获得更好的性能表现，而在透明度恢复时，子节点的位置更新标签已失效，所以不再更新位置。
此处有两个方案：
- 在透明度发生变化时连带设置其子节点的所有更新标签，但是效率太低
- 将透明度变化管理纳入到整体的更新触发中，但由于透明度级联问题，需要重构系统

**Comment by LinYunMo** [comment]
Deferring the process due to excessive changes
由于改动过大，延后处理

**Comment by LinYunMo** [comment]
考虑使用 flagChangedVersion 解决更新问题
