### ISSUE TITLE
In the new version, it is no longer possible to drag animation assets onto the Animation Controller panel as in the old version.

### ISSUE THREAD

**Issue by Voskoboyny** [cocos/cocos-engine#14705]
### Cocos Creator version

3.7.2,   3.7.1,   3.7.0,   

### System information

Windows 11

### Issue description

If you drag and drop animation assets from the Assets panel to the Animation Graph panel, the animation does not appear in the Animation Graph panel.

https://user-images.githubusercontent.com/59208948/229102079-6d4455d7-1888-4f67-a6fc-c71066b78a39.mp4

### Relevant error log output

[Window] Only animations from models can be used in animation graph. Invalid asset: {asset(21180a53-5f77-4e12-b895-96de82d811da)} 

### Steps to reproduce

1. Drag the animation to the Animation Graph tab.
2. Note that the animation is not added to the controller

[NewProject.zip](https://github.com/cocos/cocos-engine/files/11121020/NewProject.zip)

**Comment by shrinktofit** [comment]
It's by design for now -- animation controller/graph targets skeletal animations only, other types of animation are not supported. We have the dropping limit since most skeletal animations are sourcing from model files(FBX/glTF etc..).

Let me know your requirements:

- Are you trying to drag `.anim` files?

- Are your `.anim` files contains only skeletal animations?
