### ISSUE TITLE
Better support Android Large Screen devices.

### ISSUE THREAD

**Issue by minggo** [cocos/cocos-engine#15261]
In order to better support Android Large Screen devices, should do:
- declare explicit support for orientation screenSize, smallestScreenSize, and screenLayout in Manifest.xml to receive all Large Screen configuration events and avoid Activity recreation when resizable.
- resizeableActivity related configuration https://github.com/cocos/cocos-engine/issues/15057

**Comment by bofeng-song** [comment]
Only need to add smallestScreenSize to Manifest.xml

[smallestScreenSize](https://developer.android.com/guide/topics/ui/multi-window?hl=zh-cn)

**Comment by minggo** [comment]
What about onConfigurationChange event?

**Comment by bofeng-song** [comment]
> What about onConfigurationChange event?

According to the [document description](https://developer.android.com/guide/topics/large-screens/multi-window-support?hl=en), we do not need to make any modifications.
===After adding [android:configChanges](https://developer.android.com/reference/android/R.attr#configChanges), your activity and fragments receive a callback to [onConfigurationChanged()](https://developer.android.com/reference/android/app/Activity#onConfigurationChanged(android.content.res.Configuration)) instead of being destroyed and recreated. You can then manually update your views, reload resources, and perform other operations as needed.

Engine update by surfaceview's size, and resources does not need to reload

**Comment by bofeng-song** [comment]
Support config at this [PR](https://github.com/cocos/cocos-engine/pull/15763)
