### ISSUE TITLE
use const enum type in engine to reduce engine size

### ISSUE THREAD

**Issue by PPpro** [cocos/cocos-engine#15287]
![image](https://github.com/cocos/cocos-engine/assets/17872773/cf0e46a5-2b3d-4920-ad99-6c937af38840)

Need to confirm whether there is any use of value to reverse query the key of the enum object in the engine, if not, we can consider changing the entire amount to const enum

**Comment by minggo** [comment]
I don't quite understand this issue. It seems like a coding style issue. May modify all engine codes.

**Comment by PPpro** [comment]
@minggo 
on the left of captured image is the source code of ts, and the right one is the compiled output

while we use `const enum`, the output js is of much more smaller package size.
It's not the matter of coding style but the engine size.

**Comment by dumganhar** [comment]
![WeChat085c82d76a93ea057f918db91ae667a0](https://github.com/cocos/cocos-engine/assets/493372/4fef103d-e29f-4ef9-b25c-e2b6a5e02b76)

But I found that `const enum` will be optimized like the above.

I think the enums in the internal modules could use `const enums` safely while the `public` enum should not since it will break the compatibility. Yes, const enum will may package size smaller. Perhaps, we need a `switch` to open/close this feature.

**Comment by dumganhar** [comment]
inline enum funcitonality is supported in v3.8.5 but I did not check `reverse key`.
For compatibility, I think we still need to generate `reverse key enum` in a lighter way. Perhaps, write an utility/helper function for enum object to add reverse keys. For example:
```js
// Compiled enum object
var MyEnum = {
    AAA = 0,
    BBB = 1
};
reverseEnumKey(MyEnum); // Write a babel helper function to invoke `reverseEnumKey` after enum object definition.
```

**Comment by dumganhar** [comment]
[v3.8.5] Added a `Inline Enums` checkbox in building panel to indicate whether to enable `inline enums` functionality.
So close this issue now.
