### ISSUE TITLE
Canvas cannot change the event response order after setting the Priority of the Camera

### ISSUE THREAD

**Issue by zhefengzhang** [cocos/cocos-engine#16274]
### Cocos Creator version

3.8.0

### System information

window10

### Issue description

CanvasB's Camera priority is 5, and CanvasA's Camera priority is 0, but only CanvasA responds to listening events after running.

CanvasB
![图片](https://github.com/cocos/cocos-engine/assets/35944775/49526006-8036-443e-aaa6-213d7b71ef02)

CanvasA
![图片](https://github.com/cocos/cocos-engine/assets/35944775/8a19bf93-dd99-4652-a6a2-0f717986a87e)

Results:
![图片](https://github.com/cocos/cocos-engine/assets/35944775/ca83d1aa-1f7c-473c-8c00-6ee281fcdf2e)

### Relevant error log output

--

### Steps to reproduce

Download and open the project, open and run the scene-PriorityBug-Issues16274 scenario, click on the screen, observe the browser console log, you can find the problem.
--

### Minimal reproduction project
[59470.zip](https://github.com/cocos/cocos-engine/files/12645772/59470.zip)

**Comment by LinYunMo** [comment]
此项目存在两个问题：
- 由于节点未进行 layer 区分，所以所有相机都可以看到两个 canvas 并派发事件
- 如果对节点进行 layer 区分，能够保证只有一个相机派发对应的 canvas 事件

针对问题1：
> - 由于节点未进行 layer 区分，所以所有相机都可以看到两个 canvas 并派发事件

此问题由于在事件响应时，canvas 会选取一个能够渲染的相机进行时间派发，需要重构，在 https://github.com/cocos/3d-tasks/issues/12214 中进行后续跟踪

针对问题2：
> - 如果对节点进行 layer 区分，能够保证只有一个相机派发对应的 canvas 事件

在进行了节点的 layer 区分并保证相机后，事件能够正常派发，此项目中只观察到一个事件是由于本身两个 canvas 完全重叠，事件会被正常消耗掉。如果想要不消耗继续派发请使用 ```event-touch``` 中的 ```preventSwallow``` 接口


----------

There are two problems with this project:
- Since the nodes are not layer-distinguished, all cameras can see both canvas and dispatch events.
- If the nodes are layer-distinguished, it is guaranteed that only one camera will dispatch the corresponding canvas event.

For problem 1:
> If the node is layer-distinguished, it is guaranteed that only one camera dispatches the corresponding canvas event.

This issue is due to the fact that during the event response, the canvas picks a camera that can render and dispatches it at the right time, which needs to be refactored and followed up at https://github.com/cocos/3d-tasks/issues/12214.

For issue 2:
> - If nodes are layer-differentiated, it is possible to ensure that only one camera dispatches the corresponding canvas event.

After layer distinguishing the nodes and guaranteeing the cameras, the events are dispatched normally. In this project, only one event is observed because the two canvases are completely overlapping and the event will be consumed normally. If you want to continue dispatching without consuming, use the ``preventSwallow`` interface in ``event-touch``.
