### ISSUE TITLE
"Reveal in finder" function in editor doesn't show up the Window explorer in foreground

### ISSUE THREAD

**Issue by BenoitFreslon** [cocos/cocos-engine#16589]
### Use Case

Click on the asset in the Cocos Creator editor then right click then **Reveal in finder**.
On Windows 11 with CC 3.8.1 the windows explorer is hidden in background.

![image](https://github.com/cocos/cocos-engine/assets/758680/bffd7375-5e20-4ad8-ad4c-11ab722f7128)

![image](https://github.com/cocos/cocos-engine/assets/758680/83af97c4-a87a-48ce-a56b-b5913bd6bc41)

### Problem Description

The window explorer is in background and should be in foreground.

### Proposed Solution

Set the window explorer in foreground.

### Alternatives Considered

No alternative found.

**Comment by yanOO1497** [comment]
Thank you for your feedback. Indeed, we have received similar complaints and what we currently understand is that win10 users may occasionally encounter this issue, while some win11 users have reported that the issue was resolved during subsequent use, possibly due to system updates. 

This behavior primarily involves the system interface, over which we currently have no direct control at the code. Please check if there are any system update prompts and try to upgrade in a timely manner. If the issue still cannot be resolved, it may be necessary to wait for a subsequent upgrade of the editor to electron to see if that resolves the issue. Unfortunately, we cannot provide a specific timeline for this update at the moment.
