### ISSUE TITLE
spine的Bug什么版本修复

### ISSUE THREAD

**Issue by kaxifakl** [cocos/cocos-engine#16601]
1.spine原生不受UIOpacity控制，无法做animation透明度渐变
2.spine首帧未处理父级opacity

问下这两个历史悠久的Bug什么时候修复
@minggo

**Comment by kaxifakl** [comment]
@jareguo

**Comment by minggo** [comment]
Please use english in future, thanks.

**Comment by kaxifakl** [comment]
So witch version will solve spine problems?

**Comment by minggo** [comment]
We try to fix it in 3.8.3.

**Comment by zhitaocai** [comment]
seems not fix this problem in 3.8.3

**Comment by bofeng-song** [comment]
@kaxifakl @zhitaocai 
Please refer to the implementation of skeleton.ts.

Add opacity handling to _updateColor in jsb-spine-skeleton.js.

Since the subsequent modules are planned to be refactored, this issue will be fixed in the refactored version.

![image](https://github.com/cocos/cocos-engine/assets/3078423/87cf30d6-0607-4f33-a182-dcb87025dccf)

**Comment by kaxifakl** [comment]
which version is planned to ?

**Comment by bofeng-song** [comment]
@kaxifakl @zhitaocai 
This [PR ](https://github.com/cocos/cocos-engine/pull/17497)has been fixed this issue

**Comment by kaxifakl** [comment]
@bofeng-song spine还有一个问题是使用的opacity是上一帧的

**Comment by bofeng-song** [comment]
@kaxifakl 具体是web，还是native。你们有对引擎做什么改动吗

**Comment by finscn** [comment]
3.8.3并没有修复这个bug .  @minggo

**Comment by bofeng-song** [comment]
@finscn 384修复的，麻烦用384看，上面有关联的pr
