### ISSUE TITLE
Mesh support not working with spine on Canvas

### ISSUE THREAD

**Issue by wijesijp** [cocos/cocos-engine#1779]
I couldn't get mesh support working on Canvas with spine.

When I contacted spine they inform me the new version have mesh support on canvas.

Exact reply from them was

> It appears Cocos Creator copied our old Javascript runtime which does not have this setting. Please contact the Cocos Creator authors and ask if they could update to the latest spine-ts runtime

The setting mentioned is

> Experimental support for mesh attachments can be enabled by setting spine.canvas.SkeletonRenderer.useTriangleRendering to true.

Can this be added to cocos creator?.

**Comment by jareguo** [comment]
We will not support canvas mesh for now because it is not a common requirement. And the major reason is it is just an experimental feature:

> setting spine.canvas.SkeletonRenderer.useTriangleRendering to true. Note that this method is slow and may lead to artifacts on some browsers.

via http://zh.esotericsoftware.com/forum/meshes-only-works-with-WebGL-8626

> the canvas triangle renderer is highly experimental and is known not to work well in some browsers due to problems in the rendering engine of these browsers (Safari, IE, I'm looking at you). I would not recommend using this feature but instead switch to the WebGL renderer instead.

via https://github.com/EsotericSoftware/spine-runtimes/issues/750

So if you really need it, please fork the Creator engine and implement a new SGSkeletonCanvasRenderCmd.js.
