### ISSUE TITLE
Incorrect texture mapping in Progress Bar with rotated texture atlas

### ISSUE THREAD

**Issue by guardianblue** [cocos/cocos-engine#1916]
I mistakenly posted this issue onto cocos2d-js previously ([here](https://github.com/cocos2d/cocos2d-js/issues/1839)), please bear with me

The bar Sprite of ProgressBar fails to map its texture under filled mode correctly when its SpriteFrame happens to be auto-rotated in the underlying sprite sheet.

Steps to reproduce:

1. Prepare two images, one for the progress bar track and one for the bar
2. Generate a sprite sheet, forcing the texture to be rotated (e.g. by tweaking the max width property) 
3. Create a ProgressBar and assign the sprite frames
4. Set mode to **filled**
5. Test in simulator, _it should work fine_
6. Test again with mobile build, the bar would look like as if it is set as **simple** mode

**Comment by OnlyKoei** [comment]
Since we have not received similar feedback recently, this problem may have been fixed. Could you please try the latest 2.4.4 version of the engine to see if this bug still exists. Don't worry about whether the upgrade to the latest version is stable or whether there will be new problems, just to test this bug.
If there is no problem, you only consider whether to upgrade or merge some engine repairs.
If there are still problems after the test, we will follow up and deal with it.
