### ISSUE TITLE
progressBar memory leak

### ISSUE THREAD

**Issue by blocksbarcelona** [cocos/cocos-engine#1956]
ProgressBar increase memory usage with no limit. Tested on iOS (I believe it's also happening on Android).

Test project and video showing the issue: https://www.dropbox.com/sh/tp29ob9lvw8z0bs/AACajOD0uMjwCt2mQYcVvE7ba?dl=0

It is happening with with Creator: 1.3.2, 1.5.2, 1.6
tested with iOS 8, 9 in virtual and real devices (iPhone SE and iPad 3).

**Comment by jareguo** [comment]
Thanks so much for the demo and video.
This is not a real memory leak. It is because the GC is not sensitive enough on native platform. The memory will still be released after a while (or when memory is not enough).  If you need to trigger the GC immediate, just execute `cc.sys.garbageCollect();` and the memory will be released.

**Comment by jareguo** [comment]
![image](https://user-images.githubusercontent.com/1503156/30004187-27de744a-90fd-11e7-8bc0-c83f2bd093a8.png)

Even if you don't execute the `cc.sys.garbageCollect();`, the memory will still released after 7 min.

**Comment by blocksbarcelona** [comment]
I have been doing a long test (70 min) and I can confirm GC eventually works. Thanks!
