### ISSUE TITLE
Exporting to Android 

### ISSUE THREAD

**Issue by SquishyMucus** [cocos/cocos-engine#1998]
Using CocosCreator 1.6.1
I have Androind SDK 22, 23 and 25 installed

I am trying to build/publish to android.

The build step goes fine, when I try to click 'compile' I get an error. Looking inside the native.log file I get the following error:

Ant (Eclipse project) is not supported from Android SDK Tools 25.3.0.

This happens regardless of which API level I select for compilation.

**Comment by jareguo** [comment]
I think you should turn on "Android Studio".

**Comment by OnlyKoei** [comment]
hi, this problem may have been fixed because we have not received similar feedback recently. Could you please try the latest 2.4.4 version of the engine to see if this bug still exists. Don't worry about whether the upgrade to the latest version is stable or whether there will be new problems, just to test this bug.
If there is no problem, you only consider whether to upgrade or merge some engine repairs.
If there are still problems after the test, we will follow up and deal with it.
