### ISSUE TITLE
[IMPORTANT BUG] all widgets works not properly in webgl mode with canvas as target

### ISSUE THREAD

**Issue by lllyasviel** [cocos/cocos-engine#2016]
When a widget's target is the default canvas, it only works in "Canvas render mode" and fails in "WebGL mode".

Example:
![image](https://user-images.githubusercontent.com/19834515/31240011-af4f5eec-aa31-11e7-9ec5-269c4e286615.png)

![image](https://user-images.githubusercontent.com/19834515/31239592-3dd18e6c-aa30-11e7-94b9-336ea46760f6.png)
Canvas:
![image](https://user-images.githubusercontent.com/19834515/31239617-51a31b40-aa30-11e7-8aed-f5cbbd51c4d0.png)
Webgl:
![image](https://user-images.githubusercontent.com/19834515/31239636-6297fd26-aa30-11e7-99a3-f6768f53457f.png)

**Comment by ColinCollins** [comment]
1.9.1 version I built a new project in the editor， but didn't reappear this kind of problem， maybe it has been fixed by others. 

![image](https://user-images.githubusercontent.com/35832931/41153208-aeb6cabe-6b48-11e8-9c97-e9a73d25d6c2.png)
![image](https://user-images.githubusercontent.com/35832931/41153217-b2ec00c2-6b48-11e8-9d9e-0933e360ec72.png)
