### ISSUE TITLE
[BUG] Low FPS with bigger Canvas - 1.8.2rc2

### ISSUE THREAD

**Issue by blocksbarcelona** [cocos/cocos-engine#2350]
As stated in this thread: http://discuss.cocos2d-x.org/t/fps-performace-issues/41547

### Creator version?（版本号）

1.8.2rc2 but its also happening with earlier versions 1.6+ I believe.
No FPS issues on 1.5.2

### Affected platform?（受影响的平台）

OSX - High Sierra. Executing from editor and VSCode. It is happening on Chrome, Safari and Firefox.

This is happening on WebGL only. Canvas seems to work fine. Native versions (iOS/Android) works fine.

Tested with Macbook Pro late 2011
OSX: High Sierra (10.13.2)
memory: 16Gb 1333Mhz DDR3
Processor: 2.4Ghz intel Core i5

### How to reproduce?（如何重现）

1) open https://github.com/cocos-creator/example-cases
2) open scene ScrollView.fire
3) Change Canvas Design resolution to 1600 x 900
4) play and check FPS

With CC 1.5.2 im getting 55-60 fps
With CC 1.7.2 and 1.8.2rc2 im getting 25-29FPS

**Comment by jareguo** [comment]
A possible reason: http://discuss.cocos2d-x.org/t/fps-performace-issues/41547/16?u=jare

**Comment by pandamicro** [comment]
Hi, @jrosich thanks for noticing and keep testing this issue, I reviewed all the differences and found the reason.

## Direct reason

Here is the thing, v1.5 was using antialias option to create 3d context, it's set to false on desktop

https://github.com/cocos-creator/engine/blob/v1.5/cocos2d/core/CCGame.js#L676

But since then, we notice the performance issue on mobile devices, so we removed this option entirely. I thought it was by default false because it fixed our performance issue, but actually I was wrong. This option is by default turned on by Chrome, and causing the issue you report.

## Real problem

After some investigation, it seems all browsers don't treat this option the same way, some use false default value, some have a GPU blacklist to bailout all devices that doesn't support GPU level MSAA.

This lead me to the backend implementation of antialiasing: MSAA ([Multisample anti aliasing](https://en.wikipedia.org/wiki/Multisample_anti-aliasing)). I think Chrome implemented software level MSAA when GPU MSAA is not available, which will cause huge pixel fill rate and serious performance dropdown.

This is my finding for now, I will make a PR to set antialias option to false, we will see how we provide possibility to modify this value.

## External infos

- https://www.khronos.org/webgl/public-mailing-list/public_webgl/1211/msg00196.php
- https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/sampleCoverage
- https://answers.unity.com/questions/1232366/webgl-antialiasing.html
- https://stackoverflow.com/questions/23501703/can-i-programmatically-enable-webgl-antialiasing-on-firefox

**Comment by blocksbarcelona** [comment]
I have implemented myself this fix (https://github.com/cocos-creator/engine/pull/2357/files) in my 1.8.2rc2 and loaded the test project. 

Im still having performance issues on Chrome, Safari and Firefox. 

See chrome screenshot:

![screenshot 2018-02-24 13 39 49](https://user-images.githubusercontent.com/24223792/36630546-851ecb48-1968-11e8-90f1-a210b605f30c.png)

My chrome flags config:
![screenshot 2018-02-24 13 45 13](https://user-images.githubusercontent.com/24223792/36630578-fdddc39a-1968-11e8-8399-eac3535ae92d.png)

**Comment by jareguo** [comment]
Is it a scrollview specific issue? How about other scenes?

**Comment by blocksbarcelona** [comment]
It is not a scrollview specific issue. See scene EventInMask.fire from examples-cases-master resized to 1600x900 (design resolution - canvas).
It has 55-60fps with 1.5.2
![screenshot 2018-02-24 15 37 02](https://user-images.githubusercontent.com/24223792/36631487-14275610-1979-11e8-964c-41367f9f5e41.png)

And 25-30 fps with 1.8.2rc2 and the fix (https://github.com/cocos-creator/engine/pull/2357/files) 
![screenshot 2018-02-24 15 39 06](https://user-images.githubusercontent.com/24223792/36631493-2ad2a590-1979-11e8-852d-e3523590601e.png)

Again, this is happening with Firefox, Safari and Chrome. And I dont think it is a problem with 1 component... Its also happening with one animated scene I build (just a few sprites moving, no even a small game).

**Comment by pandamicro** [comment]
It's strange, on my chrome, 1.8.2 project with the fix have returned to 60fps, have you build the engine after changing CCGame.js source file ? If not, you need to do gulp build, or you can modify directly engine/bin/cocos2d-js-preview.js

**Comment by blocksbarcelona** [comment]
Yeah, forgot to build, sorry! It will probably work. :) I will check it now. Thanks!
Edit: it works!!! Thank you guys!! You fixed it during the weekend! You guys never stop working? @pandamicro @jareguo Great job!! :D 👍

**Comment by pandamicro** [comment]
> You guys never stop working?

haha, actually it was a working day after spring festival vacations
