### ISSUE TITLE
you need to use "--ephemeral" instead of "--instantapp" on pre-Oreo android devices

### ISSUE THREAD

**Issue by frenb** [cocos/cocos-engine#2775]
### Creator version?（版本号）
1.11-alpha.4

### Affected platform?（受影响的平台）

Mac Editor, Android build
### How to reproduce?（如何重现）
Connect to an Android 7 (nougat) device, and click the Play button on the build dialog.

### JavaScript output or error produced?（报错信息和调用栈）

Error message below. Root cause is that you need to run a different command on pre-Oreo android devices: adb install-multiple -r -t --ephemeral FILE_NAME.apk (you need to use --ephemeral instead of --instantapp) 

java.lang.IllegalArgumentException: Unknown option --instantapp
	at com.android.server.pm.PackageManagerShellCommand.makeInstallParams(PackageManagerShellCommand.java:1097)
	at com.android.server.pm.PackageManagerShellCommand.runInstallCreate(PackageManagerShellCommand.java:242)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:106)
	at android.os.ShellCommand.exec(ShellCommand.java:94)
	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:18530)
	at android.os.Binder.shellCommand(Binder.java:468)
	at android.os.Binder.onTransact(Binder.java:367)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2387)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:3147)
	at android.os.Binder.execTransact(Binder.java:565)
Error running command, return code: 1.

### Demo project?（demo 项目）
Dark Slash

**Comment by frenb** [comment]
Please associate with Google Play Instant milestone. I don't have the option to assign it to a milestone.

**Comment by wuzhiming** [comment]
@frenb Hello ,I try to change the adb command to install instant app on Android 7.0, but it always show failed to finalize session. 

![image](https://user-images.githubusercontent.com/6093737/40775166-fbf2baf4-64f9-11e8-965a-2c27cf5e2f8c.png)

**Comment by frenb** [comment]
I would consider switching over to using the instant apps command line tool, which takes care much of these issues.

The CLI present in the Instant Apps SDK versions 1.2 and above will be much easier. Download the SDK using the SDK manager (either in Android Studio or from the command line version) and add extras/google/instantapps/ia (inside your SDK folder) to your PATH.

Then you can do "ia run <something.zip>" to launch instant apps on any supported device from the command line. 

Note that if you're using an emulator, make sure the version of Google Play services on the device is up to date (you can update it from the emulator's control panel).

**Comment by wuzhiming** [comment]
Hello, @frenb

I've tried this CLI , it install and launch right on pre-Oreo devices , but it always show 'item not found' on Play Store and it also can't find on Settings/Google/Instant Apps , is that correct?

![wechatimg632](https://user-images.githubusercontent.com/6093737/41838834-162e39ea-7894-11e8-8248-0e8253891812.jpeg)
![wechatimg633](https://user-images.githubusercontent.com/6093737/41838891-3ab7cda8-7894-11e8-811a-10ff82f7b878.jpeg)

And this command works correct on Oreo , it can launch the instant app.

**Comment by thanwah** [comment]
Here is some code that will execute "ia run app.apk" for a different project:
https://github.com/google/play-instant-unity-plugin/blob/master/GooglePlayInstant/Editor/PlayInstantRunner.cs#L138

(Note that it calls java directly instead of using the "ia" wrapper script.)

Can you please clarify a few things about your pre-Oreo test environment:

- What device are you using?
- What OS version is it running?
- Are you able to run any instant apps? E.g. if you open Clash Royale's Play Store page on the device, can you successfully launch Try Now? https://play.google.com/store/apps/details?id=com.supercell.clashroyale

When you call "ia run file.apk" please also include "--debug" and let me know if there is any interesting output.

**Comment by wuzhiming** [comment]
Thanks @thanwah I've found the problem , we need to put -u param in front of apkPath ,  or it will load the url by package name 
eg:   ia run -u https://xxxx/x instant.zip ------>correct
        ia run instant.zip -u https://xxxx/x   ------>It will load the url by package name

**Comment by jareguo** [comment]
It should be fixed in 1.11.0-rc.1. Now all issues in Google Play Instant milestone are resolved.

**Comment by wuzhiming** [comment]
Hello , @frenb @thanwah 
When we pack CocosCreator to .app on Mac ，and try to run 'ia' command , something went wrong and this is the error output:

![image](https://user-images.githubusercontent.com/6093737/42088094-0117c0fa-7bcb-11e8-8fa4-7ad89d1203f8.png)

But when we start CocosCreator by Terminal (cd to 'CocosCreator.app/Contents/MacOS' and ./CocosCreator), it works correct , and we don't know Why , could you please help us to solve this problem. 

Thanks a lot.

**Comment by thanwah** [comment]
Thanks for the detailed bug report. It looks like there is an issue with the "ia" script since it tries to do "tput cols" to determine terminal width and pass it on to the JAR. We will change the script to have a fallback of not passing anything (and letting the default value of 80 be used). This will require us to release a new version of the script.

In the meantime you can work around this issue by calling "java -jar ia.jar" directly, if that works for you.

Thanks again.

**Comment by tdeck** [comment]
Hi, I'm the main developer working on the Google Play Instant CLI. Just dropping by to note that version 1.4 of the CLI has now been released in the SDK, and it fixes the issue you described with the wrapper script ([release notes](https://developer.android.com/topic/google-play-instant/release-notes)). You can either continue invoking it as a JAR or run `ia` directly.

**Comment by jareguo** [comment]
Thanks for the information.
