### ISSUE TITLE
APK size unchanged no matter what I do in refactor step

### ISSUE THREAD

**Issue by frenb** [cocos/cocos-engine#2776]
### Creator version?（版本号）
1.11-alpha.4

### Affected platform?（受影响的平台）

Mac Editor
### How to reproduce?（如何重现）
Go through record and refactor steps, keep all textures selected, and build and compile. Rename APK in /Users/bfrenkel/Documents/InstantGames/Slash/android-instant/publish/android

Go through record and refactor steps, unselect all textures, and build and compile. Compare the APKs. The APK output is always the same size.

**Comment by frenb** [comment]
Please associate with Google Play Instant milestone. I don't have the option to assign it to a milestone.

**Comment by wuzhiming** [comment]
@frenb Hello frenb, for the apk size, you may need to save the record on refactor panel and choose this record on builder panel like this.Because we support multiple records on builder panel

![image](https://user-images.githubusercontent.com/6093737/40792345-4efacdea-652c-11e8-95da-b44cc8931222.png)

**Comment by frenb** [comment]
Thank you for feedback! I'll try that

**Comment by frenb** [comment]
I don't think this is working still. APK is always the same size.

**Comment by frenb** [comment]
Correction. Tried it with alpha.5 and it appears to be working as intended.
