### ISSUE TITLE
Why many same spine objects aren't one draw call?

### ISSUE THREAD

**Issue by ghost** [cocos/cocos-engine#3920]
### Creator version?（版本号）
2.1.0

### Affected platform?（受影响的平台）
Web, Simulator

I created 10 spine boys.
10 spine boys => 10 draw calls

**Comment by smellypotato** [comment]
i think that is because your spine contains multiple sprite (eg. sprite A, sprite B). it draws one spine at a time, so it draws all sprite in one spine then draw the other spine, the draw sequence is sprite A -> sprite B -> sprite A -> sprite B instead of sprite A -> sprite A -> sprite B -> sprite B

**Comment by ghost** [comment]
@smellypotato

The sprite is texture packed.

spine-boy contains spineboy.atlas and spineboy.json and spineboy.png.

**Comment by sunnylanwanjun** [comment]
2.0.9 has add `enableBatch` field, it's used to open or close spine's batch, you can use it in `cocos creator` editor, or just set the field true or false.
But the function is just effectivity in web platform at present, native platform will be supported later.
