### ISSUE TITLE
The 'Hello World' project has an empty scene

### ISSUE THREAD

**Issue by rChaoz** [cocos/cocos-engine#5243]
### Creator version?（版本号）
Cocos Creator v2.1.2

### Affected platform?（受影响的平台）
Windows Editor (Mac Editor too probably, can't test it)

### How to reproduce?（如何重现）
Start Cocos Creator, create new project - choose "Hello World".

### Issue
The created project does have the 'HelloWorld.js' in the 'Scripts' folder as well as the 2 PNGs in the 'Texture' folder, however the scene is empty (Canvas and Camera only) and, obviously, when run, doesn't say 'Hello World'. This is the Node tree of a newly created 'Hello World' project:

![image](https://user-images.githubusercontent.com/8215371/63648501-4c610200-c739-11e9-8854-9e17d7ba22be.png)

**Comment by Marssssssss** [comment]
Thank you for raising this problem.  The truth is that you need to double click "helloworld" scene after you enter a new-created helloworld project. It is because in version 2.1.2, "helloworld" wouldn't be load automatically after you create it, which means that you need to load helloworld scene by your own. This problem has been fixed in version 2.2.0, now it will say "Hello World." when you enter this project.
