### ISSUE TITLE
[Suggestion] Default canvas position to [0, 0]

### ISSUE THREAD

**Issue by jcs090218** [cocos/cocos-engine#6043]
Is there a reason that the canvas has to be something other than [0, 0]? IMO, Centered position to [0, 0] is more direct and easier to use. Thanks!

**Comment by jareguo** [comment]
Hi, thanks for your suggestion. Moving to the center of the screen will indeed more easier and straightforward, especially when we need to adapt UIs for multi-size devices. This design is just because of historical reason ---- inheriting from Cocos2d-x, which also inherited from Cocos2d. So we didn't want to change it's underhood features. For centered position, you can just place all your nodes under the Canvas node, that will locate all nodes with [0,0] position to screen center.

**Comment by jcs090218** [comment]
Thanks for the explanation! I appreciate your work! 😄

**Comment by jareguo** [comment]
yup
