### ISSUE TITLE
Feature Request: Code indentation setting

### ISSUE THREAD

**Issue by ggarek** [cocos/cocos-engine#615]
Hey, 

  I would like to say, that if there was a possibility to change code indentation for project scripts it would be awesome! (e.g.: spaces vs tabs; number of spaces)

p.s.: Just wondering if you accept feature requests and if it is good idea to do it via github issues.

Thanks!

**Comment by nantas** [comment]
Hi,

The builtin code editor is just for quick edit and should not be used as working environment. We'll not going to add feature to that since our focus is Visual Studio Code. And it's easy to customize code indentation along with hundreds of other settings in VS Code.

All feature request is welcome! You can either post them here or post them to our international forum:
http://discuss.cocos2d-x.org/c/editors-and-tools/cocos-creator

**Comment by ggarek** [comment]
Good to know, that you accept feature requests! Thanks.

Regarding the code indentation. It is not what i meant, let me put it this way. I do not use builtin editor, i use vscode. What i meant saying about indentation is an initial code generation. When you create a script file in the Cocos Creator it generates default code and there is no way to change the indentation of generated template in Cocos Creator. It may become more inconvenient if there will be more code templates.

Anyways, it is very minor thing. 

p.s.: But if you could use `.editorconfig` for code generation it would be awesome ;)

**Comment by jareguo** [comment]
Hi, you can editor the default code in `CocosCreator.app/Contents/Resources/static/template/new-script.js`
