### ISSUE TITLE
Label not changing color on start() after restarting the scene

### ISSUE THREAD

**Issue by Quickz** [cocos/cocos-engine#7175]
### Creator version
2.4.0.

### Affected platform
Windows editor, Chrome browser.

### How to reproduce
Create a new label, attach a component with the code down below (Add the label reference as well), launch the game and press `R` key. After the launch, the label will change it's color to a green one as it should but after pressing the `R` key to restart the current scene, it won't.

```TypeScript
const {ccclass, property} = cc._decorator;

@ccclass
export default class NewClass extends cc.Component
{
    @property(cc.Label)
    private label: cc.Label = null;

    start()
    {
        this.label.node.color = new cc.Color(0, 125, 0);
        cc.systemEvent.once(cc.SystemEvent.EventType.KEY_DOWN, this.onKeyDown);
    }

    private onKeyDown = (event: { keyCode: number }) =>
    {
        if (event.keyCode == cc.macro.KEY.r)
        {
            this.restartScene();
        }
    }

    private restartScene()
    {
        let currentScene = cc.director.getScene();
        cc.director.loadScene(currentScene.name);
    }
}
```

**Comment by OnlyKoei** [comment]
Hello, tested on 2.4.0 according to your description, it can change color normally. Can you provide a demo?

**Comment by yeshao2069** [comment]
Hello, Thanks for your feedback！
We have tested on the Creator 2.4.0 version, but we find some problems.

First of all,  ”The start callback function will be triggered before the first activation of the component, which is before executing update for the first time.   “
https://docs.cocos.com/creator/manual/en/scripting/life-cycle-callbacks.html#start
So，when you restart the scene ( use  cc.director.loadScene), it may be  not work.

Secondly, "Register an callback of a specific event type on the EventTarget, the callback will remove itself after the first time it is triggered."
https://docs.cocos.com/creator/api/en/classes/SystemEvent.html#once
There may be some surprises, but this is appropriate for the way you use it in relation. Because loading scenes can be a bit time consuming, if you press the R key frequently, then there is a chance that this could lead to an unexpected situation where the listener event has been cancelled, but the scene is not yet loaded. Pressing the R key afterwards no longer has an effect.

So, you can try the following modifications:
1  
```
    start()
    {
        this.label.node.color = new cc.Color(0, 125, 0);
        cc.systemEvent.once(cc.SystemEvent.EventType.KEY_DOWN, this.onKeyDown);
    }

    onEnable()
    {
        this.label.node.color = new cc.Color(0, 125, 0);
        cc.systemEvent.once(cc.SystemEvent.EventType.KEY_DOWN, this.onKeyDown);
    }
```
  
2
```
    onEnable()
    {
        this.label.node.color = new cc.Color(0, 125, 0);
        cc.systemEvent.on(cc.SystemEvent.EventType.KEY_DOWN, this.onKeyDown);
    }
    onDisable()
    {
        cc.systemEvent.off(cc.SystemEvent.EventType.KEY_DOWN, this.onKeyDown);
    }
```
