### ISSUE TITLE
[2.4.x]  不支持Xcode 13

### ISSUE THREAD

**Issue by useobjc** [cocos/cocos-engine#9520]
### Creator version
2.4.6

### Affected platform
iOS

### How to reproduce
Build -> Run

** BUILD SUCCEEDED **

xcrun: error: Failed to locate 'instruments'.
xcrun: error: unable to find utility "instruments", not a developer tool or in PATH
Build succeed.
Deploying mode: release
Starting application.
Get simulator failed!

### 原因
Xcode 13 以后，instruments已经从xcrun命令行移除。详情可参考以下链接。

https://developer.apple.com/documentation/xcode-release-notes/xcode-13-release-notes
Deprecations
Instruments no longer includes the Energy template; use metrics reporting in the Xcode Organizer instead. (74161279)
The deprecated instruments command-line tool has been removed; instead, use xctrace. (74412969)

**Comment by yeshao2069** [comment]
确实有这个问题。

**Comment by yeshao2069** [comment]
https://github.com/cocos-creator/engine/issues/9501

**Comment by yeshao2069** [comment]
感谢你的反馈，这个问题是已知问题，目前引擎还没有适配最新的xcode13导致的报错。问题已经反馈，该issue暂时先关闭。后续会陆续跟进这个问题进度。
Thank you for your feedback, this issue is a known problem, the engine is not yet adapted to the latest xcode13 caused by the error. The problem has been feedback, the issue is closed for now. We will follow up on the progress of this issue one after another.
