### ISSUE TITLE
cc.Mask is crashed when combine tweening opacity & deactiving object

### ISSUE THREAD

**Issue by obraz29** [cocos/cocos-engine#9657]
### Creator version?（版本号）
3.3.1

### Affected platform?（受影响的平台）
All platform

### How to reproduce?（如何重现）
Hello, I'm working on a big project & the mask is usually crashed, after investigating, I found that if we disable node while tweening it's opacity, then child mask lost function. I'm sending a small test case in attachment, hope it can help you find the issue.
In the test project:
Step1. Press Hide Button
Step2. Press Show Button
See the mask lost it's function

### Demo project?（demo 项目）

<!--
### Thanks for the feedback.（感谢反馈）
--

[TestProject.zip](https://github.com/cocos-creator/engine/files/7531378/TestProject.zip)
>

**Comment by obraz29** [comment]
[TestProject.zip](https://github.com/cocos-creator/engine/files/7531376/TestProject.zip)

**Comment by obraz29** [comment]
[TestProject.zip](https://github.com/cocos-creator/engine/files/7531379/TestProject.zip)

**Comment by yeshao2069** [comment]
使用你的demo，确实有出现mask失效的问题，这个问题我们先内部反馈并处理。
另外，你这个问题，可以通过以下3种方式来处理：
方式1：注释  this.node.active = false; 这一句，问题可以避免；
方式2：在hide的时候，tween.to的时候，opacity改为 0.01 问题也可以避免；
```
tween(uiOpacity)
            .to(0.5, {opacity: 0})
            .start();
```
方式3：不使用UIOpacity组件，改为直接使用sprite.color属性
```
    show() {
        this.node.active = true;
        
        let sprColor = this.node.getComponent(Sprite)!.color;
        tween(sprColor)
        .to(0.5, {a: 255})
        .start();
    }
    hide() {
        let sprColor = this.node.getComponent(Sprite)!.color;
        tween(sprColor)
        .to(0.5, {a: 0})
        .start();

        this.node.active = false;
    }
```

Using your demo, there is indeed the problem of mask failure, this problem we first internal feedback and processing.
In addition, you this problem, can be dealt with in the following 3 ways.
way 1: comment this.node.active = false; this sentence, the problem can be avoided.
way 2: when hide, tween.to, opacity to 0.01 can also be avoided.
Way 3: do not use the UIOpacity component, instead of using the sprite.color property directly

**Comment by yeshao2069** [comment]
感谢你的反馈，这个应该是一个bug导致的，我已经内部反馈了，该issue暂时关闭，后续有处理情况，我在本条issue上继续追加。
Thank you for your feedback, this should be a bug caused by, I have internal feedback, the issue is temporarily closed, the subsequent processing situation, I continue to add on this issue.
